### ISSUE TITLE
Too Hard Enemies on Floor 1 (Threed)?

### ISSUE THREAD

**Issue by TheT113** [stochaztic/eb-randomizer#12] opened 2019-06-06 19:49 UTC
Seed: https://earthbound.app/?version=39.3&seed=23254645&flags=abcd2gim2np2su27w2

On Floor 1, I got to Threed, and while most of Threed had the standard Floor 1 enemies, when I went up to the area near the Graveyard to get the item there, I encountered... I think Ghost of Starmans? Is this normal behaviour, is that area supposed to be outside the zone? If so, that's a weird choice?

**Comment by stochaztic** [comment] 2019-06-06 22:03
It is currently an undocumented feature that the entire graveyard zone is associated with the floor of whatever is on the other side of the zombies. Graveyards are spooky. Since there is no accessibility to a door in this area, it can't block progress, and it can lead to occasional benefits as the strength of the present is associated with that floor as well. I am open to reconsidering this feature, however.

**Comment by TheT113** [comment] 2019-06-06 22:14
What is the definition of "whatever is on the other side of the zombies"? Is it possible to get those zombies to move? I assumed that wasn't the case in the randomizer.

**Comment by stochaztic** [comment] 2019-06-06 22:52
It is not (in Ancient Cave). The area on the other side of the zombies is a one-exit cluster, that could appear on any floor as a dead-end.

**Comment by TheT113** [comment] 2019-06-06 23:51
That's a little odd. To summarize, it basically means, you might fight harder enemies, for a chance at an item that is also a higher Floor item?

**Comment by stochaztic** [comment] 2019-06-07 00:30
That possibility exists, yes.

**Comment by stochaztic** [comment] 2019-07-01 17:31
Closed as intended.

**Closed as completed by stochaztic** 2019-07-01 17:31 UTC
